version: "3"

services:
  db-postgres-event:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-event"
    restart: always
    volumes:
      - ./database-events:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  database-events:
